[package]
name = "json_response"
version = "0.1.0"
edition = "2021"

[features]
default = ["derive"]
derive = ["json_response_derive"]

[dependencies]
salvo = "0.75.0"
json_response_derive = { path = "json_response_derive", optional = true }
serde = "1.0.217"
serde_json = "1.0.134"
